### ISSUE TITLE
Function name should be lowercase

### ISSUE THREAD

**Issue by alichtman** [shobrook/syntaxis#1]
https://github.com/shobrook/ast-lib/blob/f2f9fcda479773b9cfd0274eb07739e42a6df45b/lib/algorithms.py#L293

**Comment by alichtman** [comment]
Unless `Call` is a proper noun.

Maybe ignore this? idk, your call

**Comment by shobrook** [comment]
That class inherits from `ast.NodeVisitor`, and my definition of `visit_Call` is overriding theirs. So nah, it's not my call, and it's not your call – it's the [ast module's](https://docs.python.org/3/library/ast.html#ast.NodeVisitor) call.
